name: My Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run some script
        run: |
          echo "Running on the self-hosted runner"
          # Add any other commands you need
