name: demo-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate output.txt file
        run: |
          echo "Hello, this is the build output." > output.txt
          ls -la  # Verify file existence

      - name: Debug: Verify output.txt
        run: cat output.txt

      - name: Upload build artifact (output.txt)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: output.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the deploy job runs after the build job finishes successfully
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Deploy to server (example)
        run: |
          echo "Deploying application..."
          # Add your deployment steps here, like copying files to a server
          # Example: rsync, scp, or any deployment script you use
          # scp -r ./your-app user@your-server:/path/to/deploy
