name: demo-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run as a sample job
        run: echo hello world

      # Upload build artifacts (e.g., a compiled file, report, etc.)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./your-build-output-directory  # Replace with the actual path of your build artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that deploy runs after build job finishes successfully
    steps:
      - uses: actions/checkout@v4  # Optional, to pull code for deployment
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          
      - name: Deploy to server (example)
        run: |
          echo "Deploying application..."
          # Deploy your application using the downloaded artifacts
          # Example: scp, rsync, or any deployment script you use
          # scp -r ./downloaded-artifact/* user@your-server:/path/to/deploy
