name: demo-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate output.txt file
        run: echo "Hello, this is the build output." > output.txt

      - name: Verify output.txt file
        run: cat output.txt  # Optional: Display the contents for debugging

      - name: Upload build artifact (output.txt)
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: output.txt  # Uploads the generated file

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./deployed-files

      - name: Verify downloaded artifacts
        run: ls -la ./deployed-files && cat ./deployed-files/output.txt

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: "/path/to/deploy"
        run: |
          echo "Starting deployment..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp ./deployed-files/output.txt $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          echo "Deployment completed successfully!"
