name: demo-actions
on:
   push:
      branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions checkout@v4
     - name : Run as a sample job
     - run: echo hello world
