name: demo-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate output.txt file
        run: |
          echo "Hello, this is the build output." > output.txt
          ls -la  # Verify file existence

      - name: Upload build artifact (output.txt)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: output.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build job
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./deployed-files  # Store in a directory

      - name: Verify downloaded artifacts
        run: ls -la ./deployed-files && cat ./deployed-files/output.txt

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: "/path/to/deploy"
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

          echo "Deploying application..."
          scp ./deployed-files/output.txt $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          echo "Deployment completed successfully!"
