name: demo-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run as a sample job
        run: echo hello world

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the deploy job runs after the build job finishes successfully
    steps:
      - uses: actions/checkout@v4  # Optional, if you need to pull code for deployment
      - name: Deploy to server (example)
        run: |
          echo "Deploying application..."
          # Add your deployment steps here, like copying files to a server
          # Example: rsync, scp, or any deployment script you use
          # scp -r ./your-app user@your-server:/path/to/deploy


